# Generated by Django 5.0 on 2024-06-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wishlist',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
