# Generated by Django 5.0 on 2024-06-26 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_contactform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='contact',
            new_name='ph_number',
        ),
        migrations.AddField(
            model_name='contactform',
            name='marked_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_by_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filed_by_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
